region = "eu-west-2"
profile = "default"
availability_zone = "eu-west-2a"
instance_type = "t2.nano"
key_name = "mykeypair"
server_name = "burp-collaborator"
zone = "doesnotexist.foo"
burp_zone = "collaborator" # This will result in collaborator.doesnotexist.foo
permitted_ssh_cidr_block = "0.0.0.0/0" # It is recommend this is changed to your IP to prevent noise from SSH scanners
domain_registered_with_other = false
